/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TradingInterface extends Interface {
    getFunction(nameOrSignature: "PRICE_PER_KWH" | "buyEnergy" | "energyToken" | "getTradeCount" | "trades"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TradeExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'PRICE_PER_KWH', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyEnergy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'energyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTradeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'trades', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'PRICE_PER_KWH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyEnergy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'energyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTradeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trades', data: BytesLike): Result;
  }

  
    export namespace TradeExecutedEvent {
      export type InputTuple = [buyer: AddressLike, seller: AddressLike, kWh: BigNumberish, totalPrice: BigNumberish];
      export type OutputTuple = [buyer: string, seller: string, kWh: bigint, totalPrice: bigint];
      export interface OutputObject {buyer: string, seller: string, kWh: bigint, totalPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Trading extends BaseContract {
    
    connect(runner?: ContractRunner | null): Trading;
    waitForDeployment(): Promise<this>;

    interface: TradingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PRICE_PER_KWH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyEnergy: TypedContractMethod<
      [seller: AddressLike, kWh: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    energyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getTradeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    trades: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint] & {buyer: string, seller: string, kWh: bigint, totalPrice: bigint, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PRICE_PER_KWH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyEnergy'): TypedContractMethod<
      [seller: AddressLike, kWh: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'energyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTradeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'trades'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint] & {buyer: string, seller: string, kWh: bigint, totalPrice: bigint, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'TradeExecuted'): TypedContractEvent<TradeExecutedEvent.InputTuple, TradeExecutedEvent.OutputTuple, TradeExecutedEvent.OutputObject>;

    filters: {
      
      'TradeExecuted(address,address,uint256,uint256)': TypedContractEvent<TradeExecutedEvent.InputTuple, TradeExecutedEvent.OutputTuple, TradeExecutedEvent.OutputObject>;
      TradeExecuted: TypedContractEvent<TradeExecutedEvent.InputTuple, TradeExecutedEvent.OutputTuple, TradeExecutedEvent.OutputObject>;
    
    };
  }